### ISSUE TITLE
Only header is displayed

### ISSUE THREAD

**Issue by apertile** [serve-and-volley/atp-world-tour-tennis-data#1]
Cool stuff, but the .csv it generates displays only the first line. Any ideas of what could it be?

**Comment by serve-and-volley** [comment]
Can you give me what you typed into the command line?

**Comment by hannesgassert** [comment]
Same here. Command:  `python player_match_data.py Roger-Federer 1998 2014 active`. No error messages. Many thanks!

**Comment by serve-and-volley** [comment]
Yeah the ATP website changed the layout of their stat pages, so I have to painstakingly figure out the correct XPaths. Also I have to recode the Python scraping script, as it is not very elegant. Currently super busy but will get to fixing this in the near future.

**Comment by serve-and-volley** [comment]
@apertile @hannesgassert: I revised the script, with details here:
- https://github.com/serve-and-volley/atp-world-tour-tennis-data
- https://github.com/serve-and-volley/atp-world-tour-tennis-data/blob/master/python/atp_match_data_player.py

Let me know if you run into any problems and have any suggestions, thanks!
