### ISSUE TITLE
Cannot run match_scores in python 3.5 windows

### ISSUE THREAD

**Issue by Cally99** [serve-and-volley/atp-world-tour-tennis-data#12]
Trying to run with the example 

`time python match_scores.py 2016 2017`

from command window and I'm getting the following error. 

The system cannot accept the time entered.
Enter the new time:

If I set up a run configuration with Pycharm I get a different error when using a script parameter of the same command.
NameError: name 'xrange' is not defined

This behavior is with python 3.6.1

**Comment by serve-and-volley** [comment]
@Cally99: I have revised all the Python scripts and rescraped all the CSV files through the 2019 matches. In addition I updated them for Python 3. If you have no other questions you can close this issue?
