### ISSUE TITLE
Getting Player Names for Match Stats

### ISSUE THREAD

**Issue by sunandiyer** [serve-and-volley/atp-world-tour-tennis-data#14]
While scrapping player stats, I am not able to find the players name. Any idea on how to extract the winner and loser's name for each match.

**Comment by bezchristo** [comment]
Go look at the scrape_match_stats function in functions.py. You should be able to make changes there to scrape it.

**Comment by serve-and-volley** [comment]
Hi @sunandiyer, I have revised all the Python scripts and rescraped all the CSV files through the 2019 matches. In addition I updated them for Python 3. If you have no other questions you can close this issue?
