### ISSUE TITLE
Data quality issue

### ISSUE THREAD

**Issue by palexof** [serve-and-volley/atp-world-tour-tennis-data#15]
Hi,

this is a **great database**, many thanks for it! But I have a note on a data quality issue. Perhaps it can help you to make it even better.

I think it is wrong that the field match_id from the match_scores and match_stats files is not a primary key. Actually it should be. But consider the case where in a single tournament, there were 2 matches between the same players and the outcome (in terms of winner/loser) was the same. For instance if they met in the round_robin phase and later at the final. Then it is unclear which match from the match_score file corresponds to which stats from the match_stats file. 

And also in 3 cases the first match (or the second?) is completely missing from the match_stat file. As an example consider the following 14 match_id-s:

2001-605-h432-g379
2003-605-f324-a092
2004-605-f324-h432
2008-605-d643-d402
2009-306-c514-r383
2010-573-c882-r772
2011-605-f324-t786
2013-319-h571-sf41
2013-520-p701-w522
2015-410-r772-h756
2015-573-bc72-m824
2017-337-db59-f586
2017-7648-bh09-ca99
results-605-d875-gb88

The first 3 from 2001, 2003 and 2004 are the ones with missing matches from match_stats.

**Comment by serve-and-volley** [comment]
Hi @palexof, I revised all the Python scripts and also updated them for Python 3, as well as rescraped all the CSV files through the 2019 matches. In addition I have revised the definition of the `match_id`to be:
```
match_id = tourney_year + "-" + tourney_id + "-" + match_index + "-" + round_match_id + "-" + winner_player_id + "-" + loser_player_id
```

- https://github.com/serve-and-volley/atp-world-tour-tennis-data/blob/master/python/match_stats.py#L82

You can close this issue if you have no other questions?
