### ISSUE TITLE
2018-2019 Data

### ISSUE THREAD

**Issue by polal2is** [serve-and-volley/atp-world-tour-tennis-data#16]
Hi thank you very much for this nice piece of code,
I can't get the match_scores data past Auckland 2018. I get the following error:

_Traceback (most recent call last):
  File "match_scores.py", line 29, in <module>
    scrape_tourney_output = scrape_tourney(tourney_urls_scrape[i])
  File "C:\Users\Efstratios\atp-world-tour-tennis-data\python\functions.py", line 342, in scrape_tourney
    winner_slug = winner_url_split[3]
IndexError: list index out of range_

Do you have any idea how to fix this?

Many Thanks in advance !

![image](https://user-images.githubusercontent.com/6449380/51487196-f7c06780-1da2-11e9-8cc3-addcf56d1249.png)

**Comment by serve-and-volley** [comment]
@polal2is: Hi Hugo, I revised all the Python scripts and also updated them for Python 3, as well as rescraped all the CSV files through the 2019 matches. You can close this issue if you have no other questions?
