### ISSUE TITLE
Scraping Script.

### ISSUE THREAD

**Issue by paripon123** [serve-and-volley/atp-world-tour-tennis-data#28]
I'm new to the scraping realm but very interesting in the tennis data using for analysis in side project. On the scraping script, I got an 'list out of index' type of error on the Routine Command. I was running your script on Spyder and Jupyter Note book. 

# Command line input
start_year = str(sys.argv[1])
end_year = str(sys.argv[2])

This above line was the error.

best,

Paripon Thanthong

**Comment by ghost** [comment]
I think, You need to provide arguments as a year ..use something 
`python3 tournaments.py 2015 2016 `

in my case I didn't get error but it returns empty result

**Comment by serve-and-volley** [comment]
@paripon123 @technicalheist I revised all the scripts and I have updated all the CSVs for all the data through the end of 2022.
