### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sawtell** [serve-and-volley/atp-world-tour-tennis-data#3]
First off, thanks for making your project available.

This is probably my fault as I'm a python newbie. You'll see I'm using python 2.7 and installed the futures and requests packages.

When trying to import match stats I receive the following error:

```
$ python match_stats.py 2017 0

Collecting match stats data for 66 tournaments:

Index    Tourney slug       Matches
-----    ------------       -------
Traceback (most recent call last):
  File "match_stats.py", line 51, in <module>
    match_stats_data_scrape += asynchronous(match_stats_url_suffixes, scrape_match_stats, tourney_index, tourney_slug)
  File "/.../bin/atp-world-tour-tennis-data/python/functions.py", line 567, in asynchronous
    scrape_match_stats_output += future.result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 381, in __get_result
    raise exception_type, self._exception, self._traceback
IndexError: list index out of range
```

I can run `tournament.py` and `match_scores.py` without issue.

**Comment by sawtell** [comment]
Just to add to this, I assume this is the futures package I installed: https://pypi.python.org/pypi/futures/3.1.1 I used `pip install futures`

I have tried to run using python3 but get syntax errors on the `print` method.

**Comment by serve-and-volley** [comment]
@sawtell: Thanks for letting me know about this problem! So the problem is that the ATP site recently changed the layout for all the match stats pages, which means I will have to update the correct XPaths for all the data. I'll get this fixed soon, and will let you know when the `match_stats.py` script is working again.

**Comment by serve-and-volley** [comment]
@sawtell: I just revised all the Python scripts and I rescraped the site and revised all the CSV files. Let me know if you have any questions or need anything else 🍻

**Comment by sawtell** [comment]
Thanks for the updates!

I've just run the match_stats script and it's having an issue with "instanbul", index: 26

```
24       budapest           39/39 (100%)
25       estoril            38/38 (100%)
26       istanbul           30/39 (77%)Traceback (most recent call last):
  File "atp-world-tour-tennis-data/python/match_stats.py", line 51, in <module>
    match_stats_data_scrape += asynchronous(match_stats_url_suffixes, scrape_match_stats, tourney_index, tourney_slug)
  File "/Users/louis/sites/inform/data/atp-world-tour-tennis-data/python/functions.py", line 723, in asynchronous
    scrape_match_stats_output += future.result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 381, in __get_result
    raise exception_type, self._exception, self._traceback
IndexError: list index out of range
```

Assume this is the tournament: http://www.atpworldtour.com/en/scores/archive/istanbul/7163/2017/results

I can't see anything out of the ordinary other than Cilic was seeded and accepted a wildcard.

I also noticed this:
(let me know if I need to create a separate issue)

```
51       winston-salem      59/59 (100%)
52       us-open            Match stats URL problems
53       metz               39/39 (100%)
```

**Comment by serve-and-volley** [comment]
@sawtell For that 'IndexError' you will need to run that script again on the same tournament. I just ran it and I found no problems:
```
$ time python match_stats.py 2017 26

Collecting match stats data for 67 tournaments:

Index    Tourney slug       Matches
-----    ------------       -------
26       istanbul           39/39 (100%)
27       munich             38/38 (100%)
28       madrid             23/74 (31%)^Z
[1]+  Stopped                 python match_stats.py 2017 26

real	0m23.833s
user	0m0.000s
sys	0m0.000s
```

As for the 2017 US Open, you take a look at the ATP website for those results:
- http://www.atpworldtour.com/en/scores/archive/us-open/560/2017/results

you'll find that all those match stats URL's are missing.

Note that the stats from the ATP website have A LOT of errors.
