### ISSUE TITLE
Scraping Issue

### ISSUE THREAD

**Issue by mblevs** [serve-and-volley/atp-world-tour-tennis-data#30]
Fantastic work, this is a very cool project!

I tried running the "match_stats.py..." command (for 2018), and it looks like most of the matches came back with no results.

Would this indicate that the script needs to be adjusted to the ATP website?

**Comment by serve-and-volley** [comment]
Ah it looks like I will need to revise that file as the ATP site has been changed. I will update you when that is done, thanks for the heads up!

**Comment by dkontos21** [comment]
Hi serve-and-volley, this dataset is so rich particularly the match stats, well done! It seems that this scraping issue still stands, it only occurs from match_stats_2018 onwards, they definitely must have changed up the site around that time.

**Comment by serve-and-volley** [comment]
@mblevs @dkontos21 I have updated the scraping scripts to take into account the changes, and I have updated the CSVs to include all the data through 2022.
