### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by chanuser1** [serve-and-volley/atp-world-tour-tennis-data#34]
I have tried to get any of the 3 scripts to work and they work. But the data count is always zero. It seems that the problem is in the line

tourney_titles_parsed = xpath_parse(year_tree, tourney_titles_xpath)

at least in tournament.py.

Could you help me?

**Comment by serve-and-volley** [comment]
@chanuser1 I have updated all the scripts and the CSVs with data through the end of 2022.
